teams_list = [
    "boston city fc",
    "greater lowell rough diamonds",
    "hartford city fc",
    "kingston stockade fc",
    "new york shockers",
    "valeo fc",
    "atlantic city fc",
    "electric city shock sc",
    "first state fc",
    "hershey fc",
    "fc monmouth",
    "fc motown",
    "torch fc",
    "west chester united sc",
    "fc baltimore christos",
    "fc frederick",
    "northern virginia united fc",
    "philadelphia lone star fc",
    "virginia beach city fc",
    "appalachian fc",
    "georgia revolution fc",
    "georgia storm fc",
    "lsa athletico lanier",
    "metro louisville fc",
    "north alabama sc",
    "afc mobile",
    "florida roots fc",
    "jacksonville armada u23",
    "new orleans jesters",
    "pensacola fc",
    "port city fc",
    "southern states sc",
    "tallahassee sc",
    "boca raton fc",
    "central florida panthers sc",
    "miami dutch lions fc",
    "miami united fc",
    "naples united fc",
    "storm fc",
    "arkansas wolves fc",
    "dallas city fc",
    "demize npsl",
    "oklahoma city 1889 fc",
    "reign fk",
    "tulsa athletic",
    "fc brownsville",
    "coyotes fc",
    "denton diablos fc",
    "fort worth vaqueros fc",
    "irving fc",
    "katy 1895 fc",
    "laredo heat sc",
    "midland-odessa sockers fc",
    "fc buffalo",
    "cleveland sc"
    "erie commodores fc",
    "pittsburgh hotspurs",
    "rochester lancers",
    "syracuse fc",
    "carpathia fc",
    "fc columbus",
    "fc indiana",
    "fc milwaukee torrent",
    "panathinaikos chicago",
    "dakota fusion fc",
    "duluth fc",
    "joy st louis park",
    "la crosse aris fc",
    "med city fc",
    "minneapolis city sc",
    "sioux falls thunder fc",
    "academica sc",
    "contra costa fc",
    "el farolito sc",
    "fc davis",
    "napa valley 1839 fc",
    "oakland stompers",
    "sacramento gold fc",
    "sonoma county sol",
    "crossfire redmond",
    "international portland select fc",
    "osa seattle fc",
    "spokane sc shadow",
    "tacoma stars",
    "fc arizona",
    "as los angeles",
    "asc san diego",
    "high desert elite fc",
    "las vegas legends",
    "temecula fc",
    "boston bruins",
    "buffalo sabres",
    "detroit red wings",
    "florida panthers",
    "montreal canadiens",
    "ottawa senators",
    "tampa bay lightning",
    "toronto maple leafs",
    "columbus blue jackets",
    "new jersey devils",
    "new york islanders",
    "new york rangers",
    "philadelphia flyers",
    "pittsburgh penguins",
    "washington capitals",
    "arizona coyotes",
    "chicago blackhawks",
    "colorado avalanche",
    "dallas stars",
    "minnesota wild",
    "nashville predators",
    "st louis blues",
    "winnipeg jets",
    "calgary flames",
    "edmonton oilers",
    "los angeles kings",
    "san jose sharks",
    "seattle kraken",
    "vancouver canucks",
    "vegas golden knights",
    "boston celtics",
    "brooklyn nets",
    "new york knicks",
    "philadelphia 76ers",
    "toronto raptors",
    "cleveland cavaliers",
    "detroit pistons",
    "indiana pacers",
    "milwaukee bucks",
    "charlotte hornets",
    "miami heat",
    "orlando magic",
    "washington wizards",
    "denver nuggets",
    "minnesota timberwolves",
    "oklahoma city thunder",
    "portland trail blazers",
    "utah jazz",
    "los angeles clippers",
    "los angeles lakers",
    "phoenix suns",
    "sacramento kings",
    "houston rockets",
    "memphis grizzlies",
    "new orleans pelicans",
    "san antonio spurs",
    "buffalo bills",
    "miami dolphins",
    "new england patriots",
    "new york jets",
    "cincinnati bengals",
    "cleveland browns",
    "pittsburgh steelers",
    "indianapolis colts",
    "jacksonville jaguars",
    "tennessee titans",
    "kansas city chiefs",
    "las vegas raiders",
    "los angeles chargers",
    "dallas cowboys",
    "new york giants",
    "philadelphia eagles",
    "washington football team",
    "detroit lions",
    "green bay packers",
    "minnesota vikings",
    "carolina panthers",
    "new orleans saints",
    "tampa bay buccaneers",
    "los angeles rams",
    "san francisco 49ers",
    "seattle seahawks"]
